In [112]:
import numpy as np
np.set_printoptions(suppress=True)

In [113]:
c = 1
delta_x = 0.25
delta_t = 0.25
lam = c*delta_t/delta_x
L = 0.25#lam**2

t_target = 1
x_target = 1

def cond_a(x, t):
    return 0

def cond_b(x, t):
    return 0

def cond_c(x, t):
    if x <= (1/2)/delta_x:
        return delta_x*x
    else:
        return delta_x*(1/delta_x-x)
    
dims = (int(t_target/delta_t), int(x_target/delta_x))

In [114]:
a = np.array([-L, 2*(1+L), -L])
A = np.eye(dims[1]+1)
for i in range(1, dims[1]):
    A[i][i-1:i+2] = a
A_inv = np.linalg.inv(A)

In [115]:
A

array([[ 1.  ,  0.  ,  0.  ,  0.  ,  0.  ],
       [-0.25,  2.5 , -0.25,  0.  ,  0.  ],
       [ 0.  , -0.25,  2.5 , -0.25,  0.  ],
       [ 0.  ,  0.  , -0.25,  2.5 , -0.25],
       [ 0.  ,  0.  ,  0.  ,  0.  ,  1.  ]])

In [116]:
b = np.array([L/2, 1-L, L/2])
C = np.eye(dims[1]+1)
for i in range(1, dims[1]):
    C[i][i-1:i+2] = b

In [117]:
C

array([[1.   , 0.   , 0.   , 0.   , 0.   ],
       [0.125, 0.75 , 0.125, 0.   , 0.   ],
       [0.   , 0.125, 0.75 , 0.125, 0.   ],
       [0.   , 0.   , 0.125, 0.75 , 0.125],
       [0.   , 0.   , 0.   , 0.   , 1.   ]])

In [121]:
u = np.array([[0, 0, 0, 0, 0]]).T
print(u.T)
v = np.dot(C, u) + delta_t*np.array([[cond_c(x, 0) for x in np.arange(5)]]).T
w = 4*np.dot(A_inv, v)-u
print(np.round(w.T, decimals=4))
for i in range(5):
    u = v
    v = w
    w = 4*np.dot(A_inv, v)-u
    print(np.round(w.T, decimals=4))

[[0 0 0 0 0]]
[[0.     0.1224 0.2245 0.1224 0.    ]]
[[0.     0.1741 0.2815 0.1741 0.    ]]
[[0.     0.2077 0.2919 0.2077 0.    ]]
[[0.     0.2127 0.263  0.2127 0.    ]]
[[0.     0.1825 0.2068 0.1825 0.    ]]
[[0.     0.119  0.1343 0.119  0.    ]]


In [ ]:
# Rewrite this using a grid structure similar to the explicit method implementation.